asset_register/asset_register/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("azure-signin/", include("azure_signin.urls", namespace="azure_signin")),
    path("api/", include("dashboard.apiurls")),
    path("", include("dashboard.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

asset_register/dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    path("misc", views.misc_asset_view, name="misc_assets"),
    path("fobs", views.fobs_asset_view, name="fobs")
    path("disposed", views.disposed_asset_view, name="disposed_assets"),
    path("add_asset", views.add_asset_view, name="add_asset"),
    path("test_delay", views.test_delay, name="test_delay"),
    path("asset/<str:asset_id>", views.asset_view, name="asset_view"),
]

asset_register/dashboard/models.py
from typing import Any, Dict, List, Optional

from django.db import models
from django.urls import reverse
from django.utils.safestring import SafeString


class Asset(models.Model):
    STATES = (("ACTIVE", "Active"), ("DISPOSED", "Disposed"))

    ITEM_TYPE = (("MONITOR", "Monitor"), ("TV", "TV"), ("LAPTOP", "Laptop"), ("PHONE", "Phone"), ("OTHER", "Other"))

    id = models.CharField(max_length=10, primary_key=True)

    description = models.TextField(null=True)
    serial_number = models.CharField(max_length=64, null=True, blank=True)
    manufacturer = models.CharField(max_length=32, null=True, blank=True)
    metadata = models.JSONField(null=True, blank=True)
    type = models.CharField(choices=ITEM_TYPE, max_length=16, null=False)

    state = models.TextField(choices=STATES, null=False, default="ACTIVE", max_length=16)

    # Misc
    cost = models.DecimalField(null=True, max_digits=12, decimal_places=4)
    vat = models.DecimalField(null=True, max_digits=12, decimal_places=4)
    asset_keeper = models.CharField(max_length=128, null=True, blank=True)
    assigned_date = models.DateTimeField(null=True, blank=True)

    purchase_date = models.DateTimeField(null=True, blank=True)
    warranty_date = models.DateTimeField(null=True, blank=True)

    disposal_date = models.DateTimeField(null=True, blank=True)
    disposal_method = models.CharField(max_length=64, null=True, blank=True)
    disposal_sold_to = models.CharField(max_length=32, null=True, blank=True)
    disposal_sale_price = models.DecimalField(null=True, max_digits=7, decimal_places=4, blank=True)
    disposal_finance_informed = models.BooleanField(default=False)
    disposal_finance_informed_date = models.DateTimeField(null=True, blank=True)

    def __repr__(self) -> str:
        return f"<Asset {str(self)}>"

    def __str__(self) -> str:
        return f"{self.id} ({self.type})"

    @classmethod
    def create(cls, data: Dict[str, Any], allow_overwrite: bool) -> None:
        # Shouldn't really do this but am lazy
        asset_id = data["id"]
        if cls.objects.filter(id=asset_id) and not allow_overwrite:
            raise Exception(f"Asset with id {asset_id} already exists")

        record = cls(**data)
        record.save()

    @classmethod
    def search(cls, filter: Optional[str] = None) -> List[Dict[str, Any]]:
        result = []

        if filter == "computer":
            call = lambda: cls.objects.filter(type__exact="LAPTOP", state__exact="ACTIVE")  # noqa E731
        elif filter == "misc":
            call = lambda: cls.objects.exclude(type__exact="LAPTOP").exclude(state__exact="DISPOSED")  # noqa E731
        elif filter == "disposed":
            call = lambda: cls.objects.filter(state__exact="DISPOSED")  # noqa E731
        else:
            call = cls.objects.all

        for obj in call():
            result.append(
                {
                    "id": obj.id,
                    "type": obj.get_type_display(),
                    "owner": obj.asset_keeper,
                    "serial": obj.serial_number,
                    "metadata": obj.string_metadata,
                    "description": obj.description,
                    "disposal_method": obj.disposal_method,
                    "view_url": reverse("asset_view", kwargs={"asset_id": obj.id}),
                    "api_url": reverse("api_asset_id", kwargs={"asset_id": obj.id}),
                }
            )

        return result

    @property
    def string_metadata(self) -> str:
        result = self.manufacturer or "UNKNOWN"
        if self.type == "LAPTOP":
            if model := self.metadata.get("model"):
                result += f" {model}"
            if ram := self.metadata.get("ram"):
                result += f" {ram}GB RAM"
            if ram := self.metadata.get("disk"):
                result += f" {ram}GB Disk"

        return result.strip()

    @property
    def html_metadata(self) -> SafeString:
        data = ""
        metadata = self.metadata or {}
        for key, value in metadata.items():
            data += f"{key}: {value}\n"

        result = f"<pre>{data.strip()}</pre>"
        return SafeString(result)

    @property
    def total_cost(self) -> float:
        result = 0.0
        if self.cost:
            result += float(self.cost)
        if self.vat:
            result += float(self.vat)
        return result

asset_register/dashboard/views.py
import json
import time

from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from .models import Asset


def index(request: HttpRequest) -> HttpResponse:
    ctx = {"nav": "computer"}
    return render(request, "active_computer_assets.html", ctx)


def misc_asset_view(request: HttpRequest) -> HttpResponse:
    ctx = {"nav": "misc"}
    return render(request, "active_misc_assets.html", ctx)


def disposed_asset_view(request: HttpRequest) -> HttpResponse:
    ctx = {"nav": "disposed"}
    return render(request, "disposed_assets.html", ctx)


def test_delay(request: HttpRequest) -> HttpResponse:
    time.sleep(10)

    return JsonResponse({"status": "ok"})


def add_asset_view(request: HttpRequest) -> HttpResponse:
    ctx = {"types": Asset.ITEM_TYPE}
    return render(request, "add_asset.html", ctx)


def asset_view(request: HttpRequest, asset_id: str) -> HttpResponse:
    obj = get_object_or_404(Asset, id=asset_id)

    ctx = {"asset": obj}
    return render(request, "asset.html", ctx)


# /api/asset  TODO should use DRF
@method_decorator(csrf_exempt, name="dispatch")
class ApiAssetView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        filter_arg = request.GET.get("filter")

        return JsonResponse({"items": Asset.search(filter_arg)})

    def post(self, request: HttpRequest) -> HttpResponse:
        try:
            json_data = json.loads(request.body)
        except ValueError:
            return JsonResponse({"error": "invalid JSON data"}, status=400)

        asset_id = json_data["id"].strip()
        allow_overwrite = request.GET.get("allow_overwrite", "false") == "true"
        if asset_id == "":
            return JsonResponse({"error": "Asset ID cannot be empty"}, status=400)

        try:
            Asset.create(json_data, allow_overwrite=allow_overwrite)
        except Exception as err:
            return JsonResponse({"error": str(err)}, status=400)

        return JsonResponse({"url": reverse("asset_view", kwargs={"asset_id": asset_id})}, status=200)

asset_register/templates/active_assets.html
{% extends "base.html" %}

{% block container %}
    <div id="app">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <div class="float-left">
                        <h1>Active Assets</h1>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'add_asset' %}" class="btn btn-primary mt-2" role="button" aria-disabled="true"><i
                                class="fas fa-plus"></i> Add Asset</a>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div id="table-filter">
                    <form>
                        <div class="form-group">
                            <label for="search">Search</label>
                            <input type="text" class="form-control" v-model="search" aria-describedby="search">
                        </div>
                    </form>
                </div>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Type</th>
                        <th scope="col">Owner</th>
                        <th scope="col">Serial</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>
                    <tbody v-cloak>
                    <tr v-for="asset in searchFilter">
                        <td><a v-bind:href="asset.view_url"><% asset.id %></a></td>
                        <td><% asset.type %></td>
                        <td><% asset.owner %></td>
                        <td><% asset.serial %></td>
                        <td><% asset.metadata %></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"
            integrity="sha256-T/f7Sju1ZfNNfBh7skWn0idlCBcI3RwdLSS4/I7NQKQ=" crossorigin="anonymous"></script>

    <script type="application/javascript">
        function search(needles, haystack) {
            for (let needle of needles) {
                if (haystack.includes(needle)) {
                    return true
                }
            }
            return false
        }

        function tryLowerCase(value) {
            try {
                return value.toLowerCase()
            } catch (e) {
                return ''
            }
        }

        const app = new Vue({
            delimiters: ["<%", "%>"],
            el: '#app',
            data: {
                assets: [],
                search: ''
            },
            computed: {
                searchFilter() {
                    let result = []
                    let needles = this.search.trim().toLowerCase().split(/[ ]+/);

                    for (let item of this.assets) {
                        if (this.search.trim() === '') {
                            result.push(item)
                            continue
                        }

                        let haystack = [
                            tryLowerCase(item.id), tryLowerCase(item.type),
                            tryLowerCase(item.metadata), tryLowerCase(item.owner),
                            tryLowerCase(item.serial)
                        ].join(" ")

                        if (search(needles, haystack)) {
                            result.push(item)
                        }
                    }

                    // Sort
                    result.sort((a, b) => (a.id > b.id) ? 1 : -1)

                    return result
                }
            },
            mounted: async function () {
                let resp = await axios.get('/api/asset')
                if (resp.status === 200) {
                    for (let item of resp.data.items) {
                        this.assets.push(item)
                    }
                }
            }
        })
    </script>
{% endblock %}

asset_register/templates/active_computer_assets.html
{% extends "base.html" %}

{% block container %}
    <div id="app">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <div class="float-left">
                        <h1>Active Computer Assets</h1>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'add_asset' %}" class="btn btn-primary mt-2" role="button" aria-disabled="true"><i
                                class="fas fa-plus"></i> Add Asset</a>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div id="table-filter">
                    <form>
                        <div class="form-group">
                            <label for="search">Search</label>
                            <input type="text" class="form-control" v-model="search" aria-describedby="search">
                        </div>
                    </form>
                </div>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Type</th>
                        <th scope="col">Owner</th>
                        <th scope="col">Serial</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>
                    <tbody v-cloak>
                    <tr v-for="asset in searchFilter">
                        <td><a v-bind:href="asset.view_url"><% asset.id %></a></td>
                        <td><% asset.type %></td>
                        <td><% asset.owner %></td>
                        <td><% asset.serial %></td>
                        <td><% asset.metadata %></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"
            integrity="sha256-T/f7Sju1ZfNNfBh7skWn0idlCBcI3RwdLSS4/I7NQKQ=" crossorigin="anonymous"></script>

    <script type="application/javascript">
        function search(needles, haystack) {
            for (let needle of needles) {
                if (haystack.includes(needle)) {
                    return true
                }
            }
            return false
        }

        function tryLowerCase(value) {
            try {
                return value.toLowerCase()
            } catch (e) {
                return ''
            }
        }

        const app = new Vue({
            delimiters: ["<%", "%>"],
            el: '#app',
            data: {
                assets: [],
                search: ''
            },
            computed: {
                searchFilter() {
                    let result = []
                    let needles = this.search.trim().toLowerCase().split(/[ ]+/);

                    for (let item of this.assets) {
                        if (this.search.trim() === '') {
                            result.push(item)
                            continue
                        }

                        let haystack = [
                            tryLowerCase(item.id), tryLowerCase(item.type),
                            tryLowerCase(item.metadata), tryLowerCase(item.owner),
                            tryLowerCase(item.serial)
                        ].join(" ")

                        if (search(needles, haystack)) {
                            result.push(item)
                        }
                    }

                    // Sort
                    result.sort((a, b) => (a.id > b.id) ? 1 : -1)

                    return result
                }
            },
            mounted: async function () {
                let resp = await axios.get('/api/asset?filter=computer')
                if (resp.status === 200) {
                    for (let item of resp.data.items) {
                        this.assets.push(item)
                    }
                }
            }
        })
    </script>
{% endblock %}

asset_register/templates/active_fobs_assets.html
{% extends "base.html" %}

{% block container %}
    <div id="app">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <div class="float-left">
                        <h1>Active Fobs Assets</h1>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'add_asset' %}" class="btn btn-primary mt-2" role="button" aria-disabled="true"><i
                                class="fas fa-plus"></i> Add Asset</a>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div id="table-filter">
                    <form>
                        <div class="form-group">
                            <label for="search">Search</label>
                            <input type="text" class="form-control" v-model="search" aria-describedby="search">
                        </div>
                    </form>
                </div>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Type</th>
                        <th scope="col">Owner</th>
                        <th scope="col">Description</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>
                    <tbody v-cloak>
                    <tr v-for="asset in searchFilter">
                        <td><a v-bind:href="asset.view_url"><% asset.id %></a></td>
                        <td><% asset.type %></td>
                        <td><% asset.owner %></td>
                        <td><% asset.description %></td>
                        <td><% asset.metadata %></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"
            integrity="sha256-T/f7Sju1ZfNNfBh7skWn0idlCBcI3RwdLSS4/I7NQKQ=" crossorigin="anonymous"></script>

    <script type="application/javascript">
        function search(needles, haystack) {
            for (let needle of needles) {
                if (haystack.includes(needle)) {
                    return true
                }
            }
            return false
        }

        function tryLowerCase(value) {
            try {
                return value.toLowerCase()
            } catch (e) {
                return ''
            }
        }

        const app = new Vue({
            delimiters: ["<%", "%>"],
            el: '#app',
            data: {
                assets: [],
                search: ''
            },
            computed: {
                searchFilter() {
                    let result = []
                    let needles = this.search.trim().toLowerCase().split(/[ ]+/);

                    for (let item of this.assets) {
                        if (this.search.trim() === '') {
                            result.push(item)
                            continue
                        }

                        let haystack = [
                            tryLowerCase(item.id), tryLowerCase(item.type),
                            tryLowerCase(item.metadata), tryLowerCase(item.owner),
                            tryLowerCase(item.serial)
                        ].join(" ")

                        if (search(needles, haystack)) {
                            result.push(item)
                        }
                    }

                    // Sort
                    result.sort((a, b) => (a.id > b.id) ? 1 : -1)

                    return result
                }
            },
            mounted: async function () {
                let resp = await axios.get('/api/asset?filter=fobs')
                if (resp.status === 200) {
                    for (let item of resp.data.items) {
                        this.assets.push(item)
                    }
                }
            }
        })
    </script>
{% endblock %}

asset_register/templates/active_misc_assets.html
{% extends "base.html" %}

{% block container %}
    <div id="app">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <div class="float-left">
                        <h1>Active Misc Assets</h1>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'add_asset' %}" class="btn btn-primary mt-2" role="button" aria-disabled="true"><i
                                class="fas fa-plus"></i> Add Asset</a>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div id="table-filter">
                    <form>
                        <div class="form-group">
                            <label for="search">Search</label>
                            <input type="text" class="form-control" v-model="search" aria-describedby="search">
                        </div>
                    </form>
                </div>

                <table class="table">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Type</th>
                        <th scope="col">Owner</th>
                        <th scope="col">Description</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>
                    <tbody v-cloak>
                    <tr v-for="asset in searchFilter">
                        <td><a v-bind:href="asset.view_url"><% asset.id %></a></td>
                        <td><% asset.type %></td>
                        <td><% asset.owner %></td>
                        <td><% asset.description %></td>
                        <td><% asset.metadata %></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"
            integrity="sha256-T/f7Sju1ZfNNfBh7skWn0idlCBcI3RwdLSS4/I7NQKQ=" crossorigin="anonymous"></script>

    <script type="application/javascript">
        function search(needles, haystack) {
            for (let needle of needles) {
                if (haystack.includes(needle)) {
                    return true
                }
            }
            return false
        }

        function tryLowerCase(value) {
            try {
                return value.toLowerCase()
            } catch (e) {
                return ''
            }
        }

        const app = new Vue({
            delimiters: ["<%", "%>"],
            el: '#app',
            data: {
                assets: [],
                search: ''
            },
            computed: {
                searchFilter() {
                    let result = []
                    let needles = this.search.trim().toLowerCase().split(/[ ]+/);

                    for (let item of this.assets) {
                        if (this.search.trim() === '') {
                            result.push(item)
                            continue
                        }

                        let haystack = [
                            tryLowerCase(item.id), tryLowerCase(item.type),
                            tryLowerCase(item.metadata), tryLowerCase(item.owner),
                            tryLowerCase(item.serial)
                        ].join(" ")

                        if (search(needles, haystack)) {
                            result.push(item)
                        }
                    }

                    // Sort
                    result.sort((a, b) => (a.id > b.id) ? 1 : -1)

                    return result
                }
            },
            mounted: async function () {
                let resp = await axios.get('/api/asset?filter=misc')
                if (resp.status === 200) {
                    for (let item of resp.data.items) {
                        this.assets.push(item)
                    }
                }
            }
        })
    </script>
{% endblock %}

asset_register/templates/asset.html
{% extends "base.html" %}

{% block container %}
    <div id="app">
        <div class="row">
            <div class="col-lg-12">
                <h1>Assets {{ asset.id }}</h1>
                <p>{{ asset.description }} - <a href="{% url 'admin:dashboard_asset_change' asset.id %}"
                                                class="btn btn-primary" role="button" aria-disabled="true"><i
                        class="fas fa-edit"></i> Edit</a></p>
                <table class="table">
                    <tbody>
                    <tr>
                        <td>Serial Number</td>
                        <td>{{ asset.serial_number }}</td>
                    </tr>
                    <tr>
                        <td>Manufacturer</td>
                        <td>{{ asset.manufacturer }}</td>
                    </tr>
                    <tr>
                        <td>Type</td>
                        <td>{{ asset.get_type_display }}</td>
                    </tr>
                    <tr>
                        <td>Metadata</td>
                        <td>{{ asset.html_metadata }}</td>
                    </tr>
                    <tr>
                        <td>State</td>
                        <td>{{ asset.get_state_display }}</td>
                    </tr>
                    <tr>
                        <td>Asset Keeper</td>
                        <td>{{ asset.asset_keeper }}</td>
                    </tr>
                    <tr>
                        <td>Assigned Date</td>
                        <td>{{ asset.assigned_date }}</td>
                    </tr>
                    <tr>
                        <td>Cost</td>
                        <td>£{{ asset.cost|floatformat:2 }}</td>
                    </tr>
                    <tr>
                        <td>VAT</td>
                        <td>£{{ asset.vat|floatformat:2 }}</td>
                    </tr>
                    <tr>
                        <td>Total Cost</td>
                        <td>£{{ asset.total_cost|floatformat:2 }}</td>
                    </tr>
                    <tr>
                        <td>Purchase Date</td>
                        <td>{{ asset.purchase_date|default_if_none:"" }}</td>
                    </tr>
                    <tr>
                        <td>Warranty Date</td>
                        <td>{{ asset.warranty_date|default_if_none:"" }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"
            integrity="sha256-T/f7Sju1ZfNNfBh7skWn0idlCBcI3RwdLSS4/I7NQKQ=" crossorigin="anonymous"></script>

    <script type="application/javascript">
        const app = new Vue({
            delimiters: ["<%", "%>"],
            el: '#app',
            data: {
                assets: []
            },
            mounted: async function () {
                let resp = await axios.get('/api/asset')
                if (resp.status === 200) {
                    console.log('assigning items')
                    for (let item of resp.data.items) {
                        console.log(this.assets)
                        this.assets.push(item)
                    }
                }
            }
        })
    </script>
{% endblock %}